name: staging
on: workflow-dispatch

concurrency:
  group: staging-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: deploy-staging
    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Stop & remove existing container
        run: docker-compose down

      - name: Build Image
        run: docker-compose build

      - name: Run container
        run: docker-compose up -d 